# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_list_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('text', 'list')]),
        ),
    ]
